monolith/views/stories.py
import datetime as dt
from random import randint

from flask import Blueprint, abort, url_for
from flask import jsonify, redirect, render_template, request

from flask_login import current_user, login_required

from monolith.classes.DiceSet import DiceSet
from monolith.database import Reaction, Story, db
from monolith.forms import StoryForm
from monolith.task import add_reaction, remove_reaction
from monolith.utility.diceutils import get_dice_sets_list
from monolith.utility.validate_story import NotValidStoryError, _check_story

from monolith.utility.telebot import send_telegram_message
from monolith.views.users import get_followed_dict

stories = Blueprint('stories', __name__)


@stories.route('/new_story', methods=['GET'])
@login_required
def _newstory():
    '''
    Prepares the initialization of the new story.

    Returns:
        200 -> a form which enables the user to start a new story with a
                given dice set (theme and #dice)
    '''
    return render_template('new_story.html', diceset=get_dice_sets_list())


@stories.route('/roll_dice', methods=['GET'])
@login_required
def _rollDice():
    '''
    Rolls the dice and enables the user to start writing a story.

    The story is created as a draft, so that it can be edited.

    Raises:
        Exception: due to eventual failures during the commit of the
            created story into the database.

    Returns:
        302 -> the user is redirected to the page in which he/she can
                start writing the story on the faces which came out.
    '''

    diceset = request.args.get('diceset', 'standard')
    dicenum = request.args.get('dicenum', 6, type=int)

    try:
        dice = DiceSet(diceset, dicenum)
        roll = dice.throw_dice()
        story = Story()
        story.text = ''
        story.theme = diceset
        story.likes = 0
        story.dislikes = 0
        story.dice_set = roll
        story.author_id = current_user.id
        db.session.add(story)
        db.session.commit()
    except Exception as e:
        print(e)
        db.session.rollback()
        abort(400)

    return redirect(url_for('stories._story_edit', storyid=story.id))


@stories.route('/stories', methods=['GET'])
def _stories(message='', marked=True, id=0, react=0):
    '''
    Returns a list of stories depending on the query parameters.

    - from/to query parameters: the user specifies from which time frame he/she
        wants the stories;
    - theme query parameter: the user specifies the theme of the dice set used in the
        stories;
    - q parameters: the user specifies a word that must be present in the stories.

    Raises:
        ValueError: the date format is not valid

    Returns:
        200 -> the list of the stories in the chosen time frame
    '''
    stories = Story.query.filter_by(deleted=False, is_draft=False)
    stories = stories.order_by(Story.date.desc())

    if stories.count() == 0:
        message = 'no stories'
    else:
        # check for query parameters
        if len(request.args) != 0:
            from_date = request.args.get('from')
            to_date = request.args.get('to')
            theme = request.args.get('theme')
            query = request.args.get('q')
            # check if the query parameters from and to
            if from_date is not None and to_date is not None:
                from_dt = None
                to_dt = None

                # check if the values are valid
                try:
                    from_dt = dt.datetime.strptime(from_date, '%Y-%m-%d')
                    to_dt = dt.datetime.strptime(to_date, '%Y-%m-%d')
                except ValueError:
                    message = 'INVALID date in query parameters: use yyyy-mm-dd'
                else:  # successful try!
                    # checks for edge cases
                    if from_dt == to_dt:
                        to_dt = from_dt + dt.timedelta(days=1)

                    if from_dt > to_dt:
                        message = 'Wrong date parameters (from-date greater ' \
                                'than to-date or viceversa)!'
                        stories = []
                    else:
                        # query the database with the given values
                        stories = stories.group_by(Story.date) \
                            .having(Story.date >= from_dt) \
                            .having(Story.date <= to_dt)
                        if stories.count() == 0:
                            message = 'no stories with the given dates'

            if theme is not None:
                t_delta = dt.datetime.now() - dt.timedelta(days=5)
                stories = stories.filter(Story.date >= t_delta)
                stories = stories.filter(Story.theme == theme)

            if query is not None:
                words = query.split(' ')
                for word in words:
                    # search for single words, case insensitive
                    stories = stories.filter(Story.text.ilike(f'%{word}%'))

    # get following users if logged
    if current_user.is_authenticated:
        template_dict = get_followed_dict(current_user.id)
    else:
        template_dict = {}

    return render_template('stories.html', message=message, stories=stories,
                           like_it_url='http://127.0.0.1:5000/stories/',
                           storyid=id, react=react, **template_dict)


@stories.route('/stories/random_story', methods=['GET'])
def _get_random_recent_story(message=''):
    '''
    Gets a random recent story. 
    
    It is checked whether there are stories written
    in the last 24 hours: if there exists a random one of them is returned, otherwise
    a random story from the database is returned.

    Returns:
        200 -> a random story chosen with the criteria described above. 
    '''

    stories = Story.query.filter_by(deleted=False, is_draft=False)
    recent_story = []

    if stories.first() is not None:
        recent_stories = stories.group_by(Story.date)

        yesterday = dt.datetime.now() - dt.timedelta(days=1)
        today_stories = recent_stories.having(Story.date >= yesterday)

        # check if there are stories posted today
        if today_stories.first() is not None:
            query_size = today_stories.count()
            # we will pick randomly between at most *pool_size* stories
            # from today
            pool_size = 5

            if pool_size > query_size:
                pool_size = query_size

            # I want to pick between the last *pool_size* elements
            # (randint returns a fixed value when using pytest, but works fine
            # in reality)
            i = randint(query_size - pool_size, query_size - 1)

            # convert the query result in list (Unfortunately, I can't apply
            # the get() method on the query)
            today_stories = [story for story in today_stories]

            recent_story.append(today_stories[i])
        else:
            message = 'no stories today. Here is a random one:'
            # (randint returns a fixed value when using pytest, but works fine
            # in reality)
            i = randint(0, stories.count() - 1)

            recent_story.append(stories.all()[i])
    else:
        message = 'no stories!'


    #if there are no recent stories, just show the "Stories" tab with the error message
    if len(recent_story) == 0:
        abort(404, message)
    else:
        return render_template('story.html', story=recent_story[0], message=message)


@stories.route('/stories/<storyid>', methods=['GET'])
@login_required
def _get_story(storyid):
    '''
    Gets the story with id <storyid>.

    Returns:
        404 -> no available story with id <storyid> has been found
        200 -> a story has been found and it is returned to the user
    '''
    q = Reaction.query.filter_by(reactor_id=current_user.id,
                                 story_id=storyid).one_or_none()
    s = Story.query.get(storyid)

    if s is None:
        abort(404, f'Story {storyid} not found')
    if s.deleted:
        abort(410, f'Story {storyid} was deleted')
    if s.author_id != current_user.id and s.is_draft:
        abort(403)  # unauthorized request

    # This check allows to count also the user's reaction even if celery
    # has not updated it yet.
    if q is not None and not q.marked:
        if q.reaction_val == 1:
            s.likes += 1
        else:
            s.dislikes += 1
    return render_template('story.html', story=s)


@stories.route('/stories/<storyid>/react', methods=['POST'])
@login_required
def _post_story_react(storyid):
    '''
    Sets a reaction to the story with id <storyid>.

    The reactions are handled as tasks from celery, allowing an asynchronous
    update of the database.

    Returns:
        200 -> the reaction has been set correctly
        400 -> a reaction to the story was already set by the user
    '''
    s = Story.query.get(storyid)

    if s is None:
        abort(404, f'Story {storyid} not found')
    if s.deleted:
        abort(410, f'Story {storyid} was deleted')
    if s.is_draft:
        abort(403)

    q = Reaction.query.filter_by(reactor_id=current_user.id,
                                 story_id=storyid).one_or_none()

    react = 1 if 'like' in request.form else -1
    removed = False
    if q is None or react != q.reaction_val:
        if q is not None and react != q.reaction_val:
            # remove the old reaction if the new one has different value
            if q.marked:
                print(current_user.id)
                remove_reaction.delay(storyid, q.reaction_val)
                removed = True
            db.session.delete(q)
            db.session.commit()
        new_reaction = Reaction()
        new_reaction.reactor_id = current_user.id
        new_reaction.story_id = storyid
        new_reaction.reaction_val = react
        db.session.add(new_reaction)
        db.session.commit()

monolith/templates/html_components/big_story_template.html
{% if story.theme == 'xmas' %}
    <div class="bg-image xmas"></div>
{% elif story.theme == 'halloween' %}
    <div class="bg-image halloween"></div>
{% elif story.theme == 'standard' %}
    <div class="bg-image standard"></div>
{% endif %}


<div class=" justify-content-center align-items-center bg-text">


    <div class="mycard transparent-bg">


        <div class="container">
            {% if story.dice_set != None %}
                <br>
                <!-- DRAFT BADGE -->
                {% if story.is_draft %}
                    <h4 class="story-text"><span class="badge badge-warning badge-pill">Draft</span></h4><br>
                {% endif %}

                <!-- DICE USED -->
                <div class="row">
                    <div class="col-sm-12 center-block text-center">
                        <h5>Dice used </h5>
                        <hr class="style2">
                    </div>
                </div>
                <div class="row">
                    {% for die in story.dice_set %}
                        <div class="col">
                            <div class="card card-block d-flex bg-transparent border border-light text-white mb-3"
                                 style="width: 8rem; height: 8rem;">
                                <div class="card-body align-items-center d-flex justify-content-center">
                                    <h5 class="card-title ">{{ die }}</h5>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% endif %} <br>

            <div class="row">
                <div class="col-sm-12 center-block text-center">
                    <h5>Story</h5>
                    <hr class="style2">
                </div>
            </div>

            <div class="row">
                <div class="col-sm-12 center-block text-center">

                    <!-- EDIT BADGE -->
                    {% if story.is_draft %}
                        {% if story.author.id == current_user.id %}
                            <a class="btn btn-warning" href="/stories/{{ story.id }}/edit">Edit</a>
                        {% endif %}
                    {% endif %}

                    <p style="text-align: justify-all">
                    <h5 class="text-justify">
                        <b>{{ story.text }}</b>
                    </h5>
                    </p >
                    <br>
                    <!-- LIKE DISLIKE, DATE, AUTHOR -->
                    {% if current_user.is_authenticated %}
                        <div class="row">
                            <div class="col-md-6"></div>
                            <div class="col-md-6">
                                <b><span id="message" class="text-danger"></span></b>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                <span style="margin-right: 1rem;">Published: <i>{{ story.date.day }}/{{ story.date.month }}/{{ story.date.year }}</i></span>
                            </div>
                            <div class="col-md-4">
                                <i name="like" class="btn btn-primary  fas fa-thumbs-up"
                                   onclick="like('{{ url_for('stories._post_story_react', storyid=story.id) }}')"></i>
                                <span class="badge badge-seconary badge-pill" id="likes"> {{ story.likes }} </span>

                                <i name="like" class="btn btn-danger fas fa-thumbs-down"
                                   onclick="dislike('{{ url_for('stories._post_story_react', storyid=story.id) }}')"></i>
                                <span class="badge badge-seconary badge-pill"
                                      id="dislikes"> {{ story.dislikes }} </span>
                            </div>
                            <div class="col-md-4">
                                Author: <a href="/users/{{ story.author.id }} "
                                           class="btn badge badge-pill badge-dark"> {{ story.author.username }} </a>
                            </div>
                        </div>
                    {% endif %}


                </div>
            </div>
        </div>
    </div>
</div>

monolith/templates/html_components/bootstrap.html
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" rel="stylesheet"/>
<script
  src="https://code.jquery.com/jquery-3.4.1.slim.js"
  integrity="sha256-BTlTdQO9/fascB1drekrDVkaKd9PkwBymMlHOiG+qLI="
  crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
<meta name="viewport" content="width=device-width, initial-scale=1">

monolith/templates/html_components/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/stories">Storytellers</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="/stories">Stories</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/new_story">New Story</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/">My Wall</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/users">Users</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/logout">Logout ({{ current_user.firstname }})</a>
            </li>
        </ul>
        <span class="navbar-text">
                <button type="button" class="btn btn-secondary fas fa-filter" id="filterButton" data-toggle="modal"
                        data-target="#filterModal"></button>
        </span>

    </div>

    <!-- Modal -->
    <div class="modal fade" id="filterModal" tabindex="-1" role="dialog"
         aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Story search filter</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">

                    <!-- Search functionality-->
                    <input type="text" id=sid placeholder="Search a story by title...">
                    <br><br>

                    <!-- date picker-->
                    <div class="row">
                        <div class="col-md-10">
                            <div class="input-daterange input-group" id="datepicker">
                                <input type="date" class="input-sm form-control" name="start" id="start"/>
                                <span class="input-group-addon">to</span>
                                <input type="date" class="input-sm form-control" name="end" id="end"/>
                            </div>
                        </div>
                    </div>
                    <br>

                    <!-- theme picker-->
                    <div class="btn-group" data-toggle="buttons">
                        <label class="btn btn-light" id="standard_set" onclick="pickSet('standard')">
                            <input type="radio" name="diceset" autocomplete="off" value="standard"
                                   style="visibility:hidden;" onclick="pickSet('standard')">
                            standard
                            <img src="/static/img/standard.png" style="height: 2em;width: 2em;">
                        </label>
                        <label class="btn btn-light" id="halloween_set" onclick="pickSet('halloween')">
                            <input type="radio" name="diceset" autocomplete="off" value="halloween"
                                   style="visibility:hidden;" onclick="pickSet('halloween')">
                            halloween
                            <img src="/static/img/halloween.png" style="height: 2em;width: 2em;">
                        </label>
                        <label class="btn btn-light" id="xmas_set" onclick="pickSet('xmas')">
                            <input type="radio" name="diceset" autocomplete="off" value="xmas"
                                   style="visibility:hidden;" onclick="pickSet('xmas')">
                            xmas
                            <img src="/static/img/xmas.png" style="height: 2em;width: 2em;">
                        </label>
                    </div>
                    <i class="fas fa-times-circle" onclick="removeSet()"></i>
                    <br><br>

                    <!-- random story-->
                    <button class="btn btn-secondary" id=rndbtn onclick="random_story()">Random recent story
                    </button>
                    <br><br>


                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-danger" id=srcbtn onclick="resetfilter()">Reset filters</button>
                    <button type="button" class="btn btn-primary" data-dismiss="modal" onclick="filter()">Filter
                    </button>

                </div>
            </div>
        </div>
    </div>

    <script>
        let set_checked

        function pickSet(setname) {
            set_checked = setname;
        }

        function removeSet() {
            if (set_checked) {
                $("#" + set_checked + "_set").removeClass("active")
                $("[name=diceset]").filter("[value='" + set_checked + "']").prop("checked", false);
                set_checked = null;
            }
        }

        function random_story() {
            window.location.replace("/stories/random_story");
        }

        function filter() {
            let input1 = document.getElementById("start");
            let input2 = document.getElementById("end");
            let search = document.getElementById("sid").value
            let query = "/stories?"

            //filter by name
            if (search) {
                query += "&q=" + search
            }

            //filter date
            if (input1.value) {
                if (!input2.value) {
                    input2.value = input1.value
                }
                query += ("&from=" + input1.value + "&to=" + input2.value)
            }

            //filter theme
            if (set_checked) {
                query += "&theme=" + set_checked
            }

            window.location.replace(query);
        }

        function resetfilter() {
            document.getElementById("start").value=null
            document.getElementById("end").value=null
            document.getElementById("sid").value=null
            removeSet()
        }

        <!-- Functions that get allow to get url parameters from the page-->
        var getUrlParameter = function getUrlParameter(sParam) {
            var sPageURL = window.location.search.substring(1),
                sURLVariables = sPageURL.split('&'),
                sParameterName,
                i;

            for (i = 0; i < sURLVariables.length; i++) {
                sParameterName = sURLVariables[i].split('=');

                if (sParameterName[0] === sParam) {
                    return sParameterName[1] === undefined ? true : decodeURIComponent(sParameterName[1]);
                }
            }
        };

        <!-- when the page is ready set the parameters to the filter form-->
        $(document).ready(function () {
            let from = getUrlParameter('from')
            let to = getUrlParameter('to')
            let q = getUrlParameter('q')
            let theme = getUrlParameter('theme')
            let filtered=false

            if(from){
                document.getElementById("start").value=from
                filtered=true
            }
            if(to){
                document.getElementById("end").value=to
                filtered=true
            }
            if(q){
                document.getElementById("sid").value=q
                filtered=true
            }
            if(theme){
                $("#" + theme+ "_set").click()
                filtered=true
            }

            if(filtered){
                $('#filterButton').removeClass('btn-secondary').addClass('btn-warning')
            }
        });

    </script>
    <script>
        var input = document.getElementById("sid")
        input.addEventListener("keyup", function (event) {
            if (event.key === 'Enter') {
                event.preventDefault();
                document.getElementById("srcbtn").click();
            }
        });
    </script>
</nav>

monolith/templates/html_components/story_draft_template.html
<li class="mycard text-light draft ">

    <div class="container">
        <div class="row">
            <div class="col-sm-12 center-block text-center">


                <p>

                <h5 class="story-text">
                    <span class="badge badge-warning badge-pill">Draft</span> <b>{{ story.text }}</b>
                </h5>
                <span style="margin-right: 1rem;">Published: <i>{{ story.date.day }}/{{ story.date.month }}/{{ story.date.year }}</i></span>

                </p >

                <i class="fas fa-thumbs-up"></i> <span
                    class="badge badge-seconary badge-pill"> {{ story.likes }} </span> <i
                    class="fas fa-thumbs-down"></i> <span
                    class="badge badge-seconary badge-pill"> {{ story.dislikes }}</span>

                {% if story.author.id == current_user.id %}
                    <a class="btn btn-danger" onclick="deleteStory({{ story.id }})">Delete</a>
                    <a class="btn btn-warning" href="/stories/{{ story.id }}/edit">Edit</a>
                {% endif %}


            </div>

        </div>

    </div>
</li><br>

monolith/templates/html_components/story_template.html
{% if story.theme == 'xmas' %}
    <li class=" text-light mycard xmas">
        {% elif story.theme == 'halloween' %}
    <li class="text-light mycard halloween">
        {% else %}
    <li class=" text-light mycard standard ">
{% endif %}

<div class="container">
    <div class="row">
        <div class="col-sm-12 center-block text-center">
            <p>
            <h5 class="story-text"><b>{{ story.text }}</b></h5>
            <span style="margin-right: 1rem;">
                Published: <i>{{ story.date.day }}/{{ story.date.month }}/{{ story.date.year }}</i>
                | by: <a href="/users/{{ story.author.id }} " class="btn badge badge-pill badge-dark"> {{ story.author.username }} </a>
            </span>
            </p >

            <i class="fas fa-thumbs-up"></i> <span
                class="badge badge-seconary badge-pill"> {{ story.likes }} </span> <i
                class="fas fa-thumbs-down"></i> <span
                class="badge badge-seconary badge-pill"> {{ story.dislikes }}</span>

            <!--<a href="{{like_it_url}}{{story.id}}/1">Like it!</a>-->

            <a class="btn btn-primary" href="/stories/{{ story.id }}">Read this
                story</a>

            {% if story.author.id == current_user.id %}
                <a href="#" class="btn btn-danger" onclick="deleteStory({{ story.id }})">Delete</a>
            {% endif %}
        </div>

    </div>

</div>
</li><br>