monolith/views/auth.py
from flask import Blueprint, Response, redirect, render_template, url_for

from flask_login import current_user, login_user, logout_user

from monolith.database import User
from monolith.forms import LoginForm


auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    '''
    Performs the login of a user. 
    It checks whether the input is the username or the e-mail address, 
    the password and performs the authentication.

    Returns:
        302 -> redirection to the user's homepage if the authentication is succesful
        200 -> the login page with the corresponding error message
    '''
    form = LoginForm()
    form.password.errors = []

    if current_user.is_authenticated:
        return redirect('/')

    if form.validate_on_submit():
        cred, password = form.data['usrn_eml'], form.data['password']

        if '@' in cred:
            user = User.query.filter_by(email=cred).one_or_none()
        else:
            user = User.query.filter_by(username=cred).one_or_none()

        if user is not None and user.authenticate(password):
            login_user(user)
            return redirect(url_for('home.index'))

        form.password.errors.append('Wrong username or password.')

    return render_template('login.html', form=form)


@auth.route('/logout')
def logout():
    '''
    Performs the logout of the user.

    Returns:
        302 -> redirection to the welcome page if a user was logged in
        203 -> notifies that the operation was not needed
    '''
    if current_user.is_authenticated:
        logout_user()
        return redirect(url_for('home.index'))

    return Response(status=203)

monolith/views/stories.py
import datetime as dt
from random import randint

from flask import Blueprint, abort, url_for
from flask import jsonify, redirect, render_template, request

from flask_login import current_user, login_required

from monolith.classes.DiceSet import DiceSet
from monolith.database import Reaction, Story, db
from monolith.forms import StoryForm
from monolith.task import add_reaction, remove_reaction
from monolith.utility.diceutils import get_dice_sets_list
from monolith.utility.validate_story import NotValidStoryError, _check_story

from monolith.utility.telebot import send_telegram_message
from monolith.views.users import get_followed_dict

stories = Blueprint('stories', __name__)


@stories.route('/new_story', methods=['GET'])
@login_required
def _newstory():
    '''
    Prepares the initialization of the new story.

    Returns:
        200 -> a form which enables the user to start a new story with a
                given dice set (theme and #dice)
    '''
    return render_template('new_story.html', diceset=get_dice_sets_list())


@stories.route('/roll_dice', methods=['GET'])
@login_required
def _rollDice():
    '''
    Rolls the dice and enables the user to start writing a story.

    The story is created as a draft, so that it can be edited.

    Raises:
        Exception: due to eventual failures during the commit of the
            created story into the database.

    Returns:
        302 -> the user is redirected to the page in which he/she can
                start writing the story on the faces which came out.
    '''

    diceset = request.args.get('diceset', 'standard')
    dicenum = request.args.get('dicenum', 6, type=int)

    try:
        dice = DiceSet(diceset, dicenum)
        roll = dice.throw_dice()
        story = Story()
        story.text = ''
        story.theme = diceset
        story.likes = 0
        story.dislikes = 0
        story.dice_set = roll
        story.author_id = current_user.id
        db.session.add(story)
        db.session.commit()
    except Exception as e:
        print(e)
        db.session.rollback()
        abort(400)

    return redirect(url_for('stories._story_edit', storyid=story.id))


@stories.route('/stories', methods=['GET'])
def _stories(message='', marked=True, id=0, react=0):
    '''
    Returns a list of stories depending on the query parameters.

    - from/to query parameters: the user specifies from which time frame he/she
        wants the stories;
    - theme query parameter: the user specifies the theme of the dice set used in the
        stories;
    - q parameters: the user specifies a word that must be present in the stories.

    Raises:
        ValueError: the date format is not valid

    Returns:
        200 -> the list of the stories in the chosen time frame
    '''
    stories = Story.query.filter_by(deleted=False, is_draft=False)
    stories = stories.order_by(Story.date.desc())

    if stories.count() == 0:
        message = 'no stories'
    else:
        # check for query parameters
        if len(request.args) != 0:
            from_date = request.args.get('from')
            to_date = request.args.get('to')
            theme = request.args.get('theme')
            query = request.args.get('q')
            # check if the query parameters from and to
            if from_date is not None and to_date is not None:
                from_dt = None
                to_dt = None

                # check if the values are valid
                try:
                    from_dt = dt.datetime.strptime(from_date, '%Y-%m-%d')
                    to_dt = dt.datetime.strptime(to_date, '%Y-%m-%d')
                except ValueError:
                    message = 'INVALID date in query parameters: use yyyy-mm-dd'
                else:  # successful try!
                    # checks for edge cases
                    if from_dt == to_dt:
                        to_dt = from_dt + dt.timedelta(days=1)

                    if from_dt > to_dt:
                        message = 'Wrong date parameters (from-date greater ' \
                                'than to-date or viceversa)!'
                        stories = []
                    else:
                        # query the database with the given values
                        stories = stories.group_by(Story.date) \
                            .having(Story.date >= from_dt) \
                            .having(Story.date <= to_dt)
                        if stories.count() == 0:
                            message = 'no stories with the given dates'

            if theme is not None:
                t_delta = dt.datetime.now() - dt.timedelta(days=5)
                stories = stories.filter(Story.date >= t_delta)
                stories = stories.filter(Story.theme == theme)

            if query is not None:
                words = query.split(' ')
                for word in words:
                    # search for single words, case insensitive
                    stories = stories.filter(Story.text.ilike(f'%{word}%'))

    # get following users if logged
    if current_user.is_authenticated:
        template_dict = get_followed_dict(current_user.id)
    else:
        template_dict = {}

    return render_template('stories.html', message=message, stories=stories,
                           like_it_url='http://127.0.0.1:5000/stories/',
                           storyid=id, react=react, **template_dict)


@stories.route('/stories/random_story', methods=['GET'])
def _get_random_recent_story(message=''):
    '''
    Gets a random recent story. 
    
    It is checked whether there are stories written
    in the last 24 hours: if there exists a random one of them is returned, otherwise
    a random story from the database is returned.

    Returns:
        200 -> a random story chosen with the criteria described above. 
    '''

    stories = Story.query.filter_by(deleted=False, is_draft=False)
    recent_story = []

    if stories.first() is not None:
        recent_stories = stories.group_by(Story.date)

        yesterday = dt.datetime.now() - dt.timedelta(days=1)
        today_stories = recent_stories.having(Story.date >= yesterday)

        # check if there are stories posted today
        if today_stories.first() is not None:
            query_size = today_stories.count()
            # we will pick randomly between at most *pool_size* stories
            # from today
            pool_size = 5

            if pool_size > query_size:
                pool_size = query_size

            # I want to pick between the last *pool_size* elements
            # (randint returns a fixed value when using pytest, but works fine
            # in reality)
            i = randint(query_size - pool_size, query_size - 1)

            # convert the query result in list (Unfortunately, I can't apply
            # the get() method on the query)
            today_stories = [story for story in today_stories]

            recent_story.append(today_stories[i])
        else:
            message = 'no stories today. Here is a random one:'
            # (randint returns a fixed value when using pytest, but works fine
            # in reality)
            i = randint(0, stories.count() - 1)

            recent_story.append(stories.all()[i])
    else:
        message = 'no stories!'


    #if there are no recent stories, just show the "Stories" tab with the error message
    if len(recent_story) == 0:
        abort(404, message)
    else:
        return render_template('story.html', story=recent_story[0], message=message)


@stories.route('/stories/<storyid>', methods=['GET'])
@login_required
def _get_story(storyid):
    '''
    Gets the story with id <storyid>.

    Returns:
        404 -> no available story with id <storyid> has been found
        200 -> a story has been found and it is returned to the user
    '''
    q = Reaction.query.filter_by(reactor_id=current_user.id,
                                 story_id=storyid).one_or_none()
    s = Story.query.get(storyid)

    if s is None:
        abort(404, f'Story {storyid} not found')
    if s.deleted:
        abort(410, f'Story {storyid} was deleted')
    if s.author_id != current_user.id and s.is_draft:
        abort(403)  # unauthorized request

    # This check allows to count also the user's reaction even if celery
    # has not updated it yet.
    if q is not None and not q.marked:
        if q.reaction_val == 1:
            s.likes += 1
        else:
            s.dislikes += 1
    return render_template('story.html', story=s)


@stories.route('/stories/<storyid>/react', methods=['POST'])
@login_required
def _post_story_react(storyid):
    '''
    Sets a reaction to the story with id <storyid>.

    The reactions are handled as tasks from celery, allowing an asynchronous
    update of the database.

    Returns:
        200 -> the reaction has been set correctly
        400 -> a reaction to the story was already set by the user
    '''
    s = Story.query.get(storyid)

    if s is None:
        abort(404, f'Story {storyid} not found')
    if s.deleted:
        abort(410, f'Story {storyid} was deleted')
    if s.is_draft:
        abort(403)

    q = Reaction.query.filter_by(reactor_id=current_user.id,
                                 story_id=storyid).one_or_none()

    react = 1 if 'like' in request.form else -1
    removed = False
    if q is None or react != q.reaction_val:
        if q is not None and react != q.reaction_val:
            # remove the old reaction if the new one has different value
            if q.marked:
                print(current_user.id)
                remove_reaction.delay(storyid, q.reaction_val)
                removed = True
            db.session.delete(q)
            db.session.commit()
        new_reaction = Reaction()
        new_reaction.reactor_id = current_user.id
        new_reaction.story_id = storyid
        new_reaction.reaction_val = react
        db.session.add(new_reaction)
        db.session.commit()

monolith/views/users.py
from flask import Blueprint, abort
from flask import jsonify, redirect, render_template, request

from flask_login import current_user, login_required, login_user

from monolith.database import Story, User, db
from monolith.forms import UserForm

from sqlalchemy import func
from sqlalchemy.exc import IntegrityError

users = Blueprint('users', __name__)


@users.route('/users')
@login_required
def users_():
    '''
    Provides the list of all the users with their last story (if any).

    Returns:
        200 -> read above
    '''
    return render_template('users.html', result=_get_users())


def _get_users(withid=False):
    last_story = db.session.query(Story.author_id, Story.text, func.max(Story.date).label('date')) \
        .group_by(Story.author_id).having(Story.is_draft == False).having(Story.deleted == False) \
        .subquery()

    res = db.session.query(User.username, last_story.c.text, last_story.c.date, User.id,) \
            .outerjoin(last_story, User.id == last_story.c.author_id).order_by(User.id.asc()).all()

    return res


@users.route('/users/<user_id>')
@login_required
def get_user(user_id):
    '''
    Opens the wall of the user with id <user_id>.

    Returns:
        200 -> the user's wall with the list of all his/her posted stories
    '''
    
    if user_id == current_user.id:
        return redirect('/')

    us = User.query.get(user_id)
    if us is None:
        abort(404, f'User {user_id} does not exist')

    stories = Story.query.filter_by(author_id=us.id,
                                    is_draft=False,
                                    deleted=False)
    stories = stories.order_by(Story.date.desc()).all()
    return render_template('get_user.html', user=us.username, userid=us.id, stories=stories, users=_get_users())


@users.route('/signup', methods=['GET', 'POST'])
def signup():
    '''
    GET
    ---
    Opens the signup page.

    Returns:
        200 -> the page has been returned

    POST
    ----
    Registers a user.

    Raises:
        IntegrityError -> there is already a user with the chosen username or e-mail address
    
    Returns:
        409 -> the exception above has been raised
        302 -> the registration was succesful and the user is redirected to its homepage
    '''
    form = UserForm()
    status = 200

    if current_user.is_authenticated:
        return redirect('/')

    if form.validate_on_submit():
        new_user = User()
        form.populate_obj(new_user)
        new_user.set_password(form.password.data)
        db.session.add(new_user)

        try:
            db.session.commit()
            login_user(new_user)
            return redirect('/')
        except IntegrityError as e:
            db.session.rollback()
            status = 409
            if 'user.username' in str(e):
                err = 'This username already exists.'
            elif 'user.email' in str(e):
                err = 'This email is already used.'

            form.email.errors.append(err)

    return render_template('signup.html', form=form), status


@users.route('/users/<user_id>/follow', methods=['DELETE', 'POST'])
@login_required
def follow(user_id):
    '''
    Adds (POST)/Removes (DELETE) the user with id <user_id> to/from the list of user 
    followed by the currently logged user. 

    If it is already in the list returns successfully without updating the database, and
    the same happens for the removal.

    All responses are in JSON format and are meant to be invokated within the
    the frontend (eg. AJAX or fetch), not by url access.

    Returns:
        400 -> the user tried to follow himself/herself
        200 -> follow/unfollow registered successfully
    '''

    followee = User.query.get(user_id)
    if followee is None:
        message = 'User with id {} does not exist'.format(user_id)
        return (jsonify(error=message), 404)

    if followee == current_user:
        return (jsonify(error='Cannot follow or unfollow yourself'), 400)

    if request.method == 'POST':
        current_user.follows.append(followee)
        db.session.commit()
        return jsonify(message='User followed')

    if request.method == 'DELETE':
        try:
            current_user.follows.remove(followee)
            db.session.commit()
        except ValueError:
            pass
        return jsonify(message='User unfollowed')


def get_followed_dict(user_id):
    me = User.query.get(user_id)
    users = [{'firstname': x.firstname, 'lastname': x.lastname, 'id': x.id, 'username': x.username}
             for x in me.follows]
    return {'users': users}


@users.route('/followed', methods=['GET'])
@login_required
def get_followed():
    '''
    Gets the list of the current user's followers.

    Returns:
        200 -> the list has been returned correctly
    '''
    template_dict = get_followed_dict(current_user.id)
    return render_template('followed.html', **template_dict)


@users.route('/bot/register', methods=['POST'])
def register():
    username = request.form.get('username')
    chat_id = request.form.get('chat_id')

    if username is not None and chat_id is not None:
        user = User.query.filter_by(username=username).one_or_none()

        if user is not None:
            user.telegram_chat_id = chat_id
            db.session.commit()
            return '', 200

        abort(404)

    abort(400)

monolith/templates/401.html
<html>
    <head>
        {% include 'html_components/bootstrap.html' %}
        <title>Unauthorized request</title>
    </head>
    <body>
        {% include 'html_components/nav.html' %}

        <div class="container">
          <h1>401</h1>
          <p>{{ message }}</p>
          {% if not current_user.is_authenticated %}
              <p>Here you can <a href="{{ url_for('auth.login') }}">Login</a> or <a href="{{ url_for('users.signup') }}">Signup</a></p>
          {% endif %}
        </div>
    </body>
</html>

monolith/templates/410.html
<html>
    <head>
        {% include 'html_components/bootstrap.html' %}
        <title>Resource does not exists anymore</title>
    </head>
    <body>
        {% include 'html_components/nav.html' %}

        <div class="container">
          <h1>410</h1>
          <p>{{ message }}</p>
        </div>
    </body>
</html>

monolith/templates/edit_story.html
<html>

<head>
    {% include 'html_components/bootstrap.html' %}
    <style>
        #is_draft {
            display: none;
        }
    </style>
    <link href="/static/css/story.css" rel="stylesheet"/>
    <link href="/static/css/background.css" rel="stylesheet"/>
</head>

<body>

<!-- ----------------- NAV BAR ------------------ -->
{% if current_user.is_authenticated %}

    {% include 'html_components/nav.html' %}

    {% if story.theme == 'xmas' %}
        <div class="bg-image xmas"></div>
    {% elif story.theme == 'halloween' %}
        <div class="bg-image halloween"></div>
    {% elif story.theme == 'standard' %}
        <div class="bg-image standard"></div>
    {% endif %}

    <div class="container d-flex flex-wrap align-items-center bg-text">
        <div class="jumbotron w-100 transparent-bg">

            <form action="/stories/{{ story_id }}/edit" method="POST" role="form" name="storyform">
                {{ form.hidden_tag() }}

                <div class="row">
                    <div class="col-sm-12 center-block text-center">
                        <h5>Current dice values </h5>
                        <hr class="style2">
                    </div>
                </div>
                <div class="row">
                    {% for die in dice %}
                        <div class="col">
                            <div class="card card-block d-flex text-white bg-transparent border border-light mb-3"
                                 style="width: 8rem; height: 8rem;">
                                <div class="card-body align-items-center d-flex justify-content-center">
                                    <h5 class="card-title ">{{ die }}</h5>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <div class="row">
                    <div class="col-sm-12 center-block text-center">
                        <br>
                        {{ form['text'].label }}
                        <br>
                        {{ form['text'](class_='form-control input-lg bg-dark text-white') }}

                        <!-- THIS FIELD IS HIDDEN -->
                        {{ form['is_draft']() }}
                        <!-- ==================== -->

                        {% for e in form['text'].errors %}
                            <p class="help-block">{{ e }}</p>
                        {% endfor %}
                        <br>

                        <button type="button" id="validate" class="btn btn-success">Submit Story</button>
                        <button type="button" id="draft" class="btn btn-primary">Submit Draft Story</button>
                        <button type="button" id="cancel" class="btn btn-danger">Cancel</button>
            </form>
        </div>
    </div>

    </div>



{% else %}
    Hi Anonymous, <a href="/login">Log in</a>
{% endif %}

</div>


<script>
    let manual_unload = false
    let storyform = document.querySelector('form')

    document.querySelector('#validate').addEventListener('click', evt => {
        manual_unload = true
        storyform.is_draft.checked = false
        storyform.submit()
    })
    document.querySelector('#draft').addEventListener('click', evt => {
        manual_unload = true
        storyform.is_draft.checked = true
        storyform.submit()
    })
    document.querySelector('#cancel').addEventListener('click', evt => {
        manual_unload = true
        fetch("{{ url_for('stories._deleteStory', storyid=story_id) }}", {method: 'DELETE'})
            .then(response => {
                window.location = "{{ url_for('stories._stories') }}"
            })
    })
    window.addEventListener('beforeunload', evt => {
        console.log('event ' + manual_unload)
        if (manual_unload) {
            return false
        }

        evt.preventDefault()
        console.log('beforeunload')
        fetch("{{ url_for('stories._deleteStory', storyid=story_id) }}", {method: 'DELETE'})
        return true
    });
</script>

</body>

</html>

monolith/templates/followed.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% include 'html_components/bootstrap.html' %}
  </head>
  <body>
    {% if current_user.is_authenticated %}
    <!--Navigation bar-->
    {% include 'html_components/nav.html' %}
    <!--end of Navigation bar-->

    <div class="container">
      <h2>Followed users</h2>

      <ul class="list-unstyled">
        {% for user in users %}
        <li id="user_{{user.id}}">
          <a class="text-muted btn" disabled="true" href="/users/{{user.id}}">{{user.firstname}} {{user.lastname}}</a>
          <button type="button" class="btn btn-sm btn-outline-danger" onclick="unfollow({{user.id}})">Unfollow</button>
        </li>
        {% endfor %}
      </ul>
    </div>

    {% else %}
    Hi Anonymous, <a href="/login">Log in</a> or <a href="/signup">Sign Up</a>
    {% endif %}
  </body>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>

  <script>
    function unfollow(id) {
      fetch('/users/' + id + '/follow', {method: 'DELETE'})
        .then(function (response) {
          if (response.ok) {
            let name = $('#user_' + id + ' a').text()
            let alert = `
              <div class="alert alert-info alert-dismissible fade show" role="alert">
                ${name} unfollowed
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>`
            $('#user_' + id).html(alert)
          } else {
            console.log('invalid unfollow operation')
          }
        })
    }
  </script>

</html>

monolith/templates/get_user.html
<html>

<head>
    {% include 'html_components/bootstrap.html' %}
    <link href="/static/css/story.css" rel="stylesheet"/>
    <!-- Custom styles for this template -->
    <link href="/static/css/sidebar.css" rel="stylesheet">
    <title>{{ user }}'s wall</title>
</head>
<body>

<!--Navigation bar-->
{% include 'html_components/nav.html' %}

<!--end of Navigation bar-->
<div class="container-fluid">
    <div class="d-flex" id="wrapper">

        <!-- Sidebar -->
        <div class="bg-white border-right" id="sidebar-wrapper" id="sidebar-wrapper">
            <i class="fas fa-angle-left fa-2x togglebutton" id="menu-toggle"></i>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <br>

            <h4>Users</h4>

            <div class="list-group list-group-flush">
                {% for usr in users %}
                    <div class="list-group-item d-flex justify-content-between align-items-center"
                         id="user_{{ usr.id }}">
                        <a class="text-dark btn" disabled="true"
                           href="/users/{{ usr.id }}">{{ usr.username }}</a>
                        {% if usr[1]: %}
                        <button type="button" class="badge badge-dark badge-pill btn" data-toggle="modal"
                                data-target="#user_{{ usr.id }}_last_story">
                            Last Story
                        </button>
                        {% endif %}
                    </div>

                    <!-- user last story -->
                    {% if usr[1]: %}

                        <div class="modal fade" id="user_{{ usr.id }}_last_story" tabindex="-1" role="dialog"
                             aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                            <div class="modal-dialog modal-dialog-centered" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLongTitle">Last story from {{ usr.username }}</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        {{ usr[1] }} <br> <br>
                                        Published: <i>{{ usr[2].day }}/{{usr[2].month }}/{{usr[2].year }}</i>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endif %}


                {% endfor %}
            </div>
        </div>
        <!-- /#sidebar-wrapper -->

        <h5>{{ message }}</h5>
        <div class="jumbotron bg-white" id="page-content-wrapper">

            <h5>{{ user }}'s Wall</h5>
            <hr class="style1">

            {% if userid != current_user.id %}
                <a href="#" class="btn btn-secondary"
                   onclick="follow({{ userid }})">Follow author</a>
                <br><br>
            {% endif %}


            <ul class="list-group">
                <div class="row">
                    {% for story in stories: %}
                        <div class="col-md-12">
                            {% include 'html_components/story_template.html' %}
                        </div>
                    {% endfor %}
                </div>

            </ul>

        </div>
    </div>
</div>

<script>
    function follow(user_id) {
        fetch('/users/' + user_id + '/follow', {method: 'POST'})
            .then(function (response) {
                if (response.ok) {
                    alert('Now following user ' + user_id)
                    location.reload();
                } else {
                    console.log('Invalid follow request to user: ' + user_id)
                }
            });
    }

    function deleteStory(story_id) {
        fetch('/stories/' + story_id, {method: 'DELETE'})
            .then(response => response.json())
            .then(data => {
                alert(data.message)
                window.location.replace('/stories');
            });
    }
</script>
<script>
    $("#menu-toggle").click(function (e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
        if (!$("#wrapper").hasClass("toggled")) {
            $("#menu-toggle").addClass("toggled");
            $("#menu-toggle").addClass("fa-angle-left");
            $("#menu-toggle").removeClass("fa-angle-right");
        } else {
            $("#menu-toggle").removeClass("toggled");
            $("#menu-toggle").removeClass("fa-angle-left");
            $("#menu-toggle").addClass("fa-angle-right");
        }

    });

</script>

</body>
</html>

monolith/templates/login.html
<html>
<head>
    {% include 'html_components/bootstrap.html' %}
</head>
<body>
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}
    Login
{% endblock %}
{% block content %}
    {{ super() }}

    <div class="container">
        <div class="row">
            <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
                <div class="card card-signin my-5">
                    <div class="card-body">

                        <h1>Sign up</h1>
                        <br>
                        <form action="" method="POST">
                            {{ form.hidden_tag() }}
                            <dl>
                                {% for field in form.display %}
                                    <dt>{{ form[field].label }}</dt>
                                    <dd>{{ form[field]() }}</dd>
                                    {% if form[field].errors %}
                                        {% for e in form[field].errors %}
                                            <p class="help-block">{{ e }}</p>
                                        {% endfor %}
                                    {% endif %}
                                {% endfor %}
                            </dl>
                            <p>
                                <input class="btn btn-primary" type=submit value="Login">
                        </form>

                        <span class="txt1 p-b-9">
                    Don’t have an account?
                </span>
                        <a class="txt3" href="/signup">
                            Sign up now
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
</body>
</html>